### ISSUE TITLE
`eeprom_driver.c` will not compile for xmega E devices

### ISSUE THREAD

**Issue by fake-name** [alexforencich/xboot#10]
Basically, it seems like Atmel is trying to depreciate 'NVM_CMD_READ_EEPROM_gc', 'NVM_CMD_LOAD_EEPROM_BUFFER_gc', 'NVM_CMD_READ_EEPROM_gc' and 'NVM_CMD_LOAD_EEPROM_BUFFER_gc'.

In any event, they've removed them from the available commands for the NVM controller on xmega E devices.

Is there any reason xboot is using it's own EEPROM driver, rather then the EEPROM functions in `<avr/eeprom.h>`? The functions in `<avr/eeprom.h>` seem to be written in assembly (assuming I'm looking at the correct source files).

Is it a code-size issue?

**Comment by nickdademo** [comment]
Also running into this issue with the XMEGA 32E5.

@fake-name : Did you end up just using the AVR EEPROM header (avr/eeprom.h)?

**Comment by fake-name** [comment]
@nickdademo - I wound up just flat-out not using xboot at all.

**Comment by nickdademo** [comment]
Thanks for the reply - did you end up rolling your own then?

**Comment by fake-name** [comment]
No, I just reworked the mechanical design so I could expose the programming interface in a way that let me update it that way.

It was for a one-off project anyways.

Sorry!

**Comment by nickdademo** [comment]
Added XMEGA E5 support in this PR: https://github.com/alexforencich/xboot/pull/17

Tested and working with XMEGA32E5 (including XBoot API).

**Comment by fake-name** [comment]
I'll close this if/when #17 gets merged.

**Comment by alexforencich** [comment]
#17 has been tested and merged.
